name = "critteria"
main = "./dist/worker/index.js"
compatibility_date = "2026-07-30"

[assets]
directory = "./"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "critteriamulti"
database_id = "4631766e-d5c9-4376-a327-bbdda88419cc"
